service: throw-away-kotlin-lambda

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: java8

package:
  artifact: build/distributions/tech-when-service.zip

functions:
  currentTime:
    handler: com.techwhen.Handler
    events:
      - http:
          path: conferences
          method: get